-- P0004 Hub: workspace projects, memberships, activity, legacy ID maps (Phase 0)

-- Projects (Todo/Data Box compatible: bigint id + source_ref for multi-origin import)
create table if not exists public.projects (
  id bigint generated by default as identity primary key,
  name text not null,
  color text,
  created_by uuid references auth.users (id) on delete set null,
  source_ref text not null default 'manual',
  legacy_project_id bigint,
  created_at timestamptz not null default now(),
  updated_at timestamptz,
  constraint projects_source_legacy_unique unique (source_ref, legacy_project_id)
);

create index if not exists projects_source_ref_idx on public.projects (source_ref);
create index if not exists projects_name_idx on public.projects (name);

create table if not exists public.project_members (
  project_id bigint not null references public.projects (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (project_id, user_id)
);

create index if not exists project_members_user_id_idx on public.project_members (user_id);

create table if not exists public.activity_logs (
  id bigint generated always as identity primary key,
  user_id uuid references auth.users (id) on delete set null,
  action text,
  details jsonb,
  created_at timestamptz not null default now()
);

create index if not exists activity_logs_user_id_idx on public.activity_logs (user_id);
create index if not exists activity_logs_created_at_idx on public.activity_logs (created_at desc);

-- Map legacy Supabase project user UUID → Hub auth.users UUID
create table if not exists public.legacy_user_map (
  source_ref text not null,
  legacy_user_id uuid not null,
  hub_user_id uuid not null references auth.users (id) on delete cascade,
  email text,
  migrated_at timestamptz not null default now(),
  primary key (source_ref, legacy_user_id)
);

create index if not exists legacy_user_map_email_idx on public.legacy_user_map (source_ref, email);

create index if not exists legacy_user_map_hub_user_id_idx on public.legacy_user_map (hub_user_id);

create table if not exists public.legacy_project_map (
  source_ref text not null,
  legacy_project_id bigint not null,
  hub_project_id bigint not null references public.projects (id) on delete cascade,
  migrated_at timestamptz not null default now(),
  primary key (source_ref, legacy_project_id)
);

alter table public.profiles add column if not exists default_project_id bigint;

-- RLS
alter table public.projects enable row level security;
alter table public.project_members enable row level security;
alter table public.activity_logs enable row level security;
alter table public.legacy_user_map enable row level security;
alter table public.legacy_project_map enable row level security;

drop policy if exists "projects_select_authenticated" on public.projects;
create policy "projects_select_authenticated"
on public.projects for select to authenticated
using (
  exists (
    select 1 from public.profiles me
    where me.id = auth.uid() and me.role in ('admin', 'manager')
  )
  or exists (
    select 1 from public.project_members pm
    where pm.project_id = projects.id and pm.user_id = auth.uid()
  )
);

drop policy if exists "projects_write_admin" on public.projects;
create policy "projects_write_admin"
on public.projects for all to authenticated
using (
  exists (select 1 from public.profiles me where me.id = auth.uid() and me.role = 'admin')
)
with check (
  exists (select 1 from public.profiles me where me.id = auth.uid() and me.role = 'admin')
);

drop policy if exists "project_members_select" on public.project_members;
create policy "project_members_select"
on public.project_members for select to authenticated
using (
  user_id = auth.uid()
  or exists (select 1 from public.profiles me where me.id = auth.uid() and me.role in ('admin', 'manager'))
);

drop policy if exists "project_members_write_admin" on public.project_members;
create policy "project_members_write_admin"
on public.project_members for all to authenticated
using (
  exists (select 1 from public.profiles me where me.id = auth.uid() and me.role = 'admin')
)
with check (
  exists (select 1 from public.profiles me where me.id = auth.uid() and me.role = 'admin')
);

drop policy if exists "activity_logs_select" on public.activity_logs;
create policy "activity_logs_select"
on public.activity_logs for select to authenticated
using (
  user_id = auth.uid()
  or exists (select 1 from public.profiles me where me.id = auth.uid() and me.role in ('admin', 'manager'))
);

drop policy if exists "legacy_maps_admin_select" on public.legacy_user_map;
create policy "legacy_maps_admin_select"
on public.legacy_user_map for select to authenticated
using (
  exists (select 1 from public.profiles me where me.id = auth.uid() and me.role in ('admin', 'manager'))
);

drop policy if exists "legacy_project_maps_admin_select" on public.legacy_project_map;
create policy "legacy_project_maps_admin_select"
on public.legacy_project_map for select to authenticated
using (
  exists (select 1 from public.profiles me where me.id = auth.uid() and me.role in ('admin', 'manager'))
);

grant select, insert, update, delete on public.projects to authenticated;
grant select, insert, update, delete on public.project_members to authenticated;
grant select, insert on public.activity_logs to authenticated;
grant select on public.legacy_user_map to authenticated;
grant select on public.legacy_project_map to authenticated;
